### ISSUE TITLE
Return portal not generating using sponge.

### ISSUE THREAD

**Issue by Pixelmnkey** [Shinoow/The-Beneath#11] opened 2018-06-04 16:15 UTC
Hey there! I'm using sponge right now and the beneath teleporter won't spawn once you reach that dimension, it was working fine without sponge no idea if I should post it over there.

Any fix to that ? Thanks!

**Comment by Shinoow** [comment] 2018-06-17 12:44
Duplicate of #10

**Closed as completed by Shinoow** 2018-06-17 12:44 UTC
Labels: duplicate
